# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Xiaohang ZHANG
title: PhD candidate
email: zhxh96@gmail.com
website: zhxh233.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  zhxh233
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0001-6402-7155

# Additional icon links
additional_links:
- title: GitHub
  icon: fas fa-globe
  url: https://github.com/zhxh233
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a PhD candidate who is focus on bioinformatics, especieally in comparative genomics. 
  Interested in machine learning and artificial intelligence。

  I am most skilled in: <mark>Python</mark>, <mark>R</mark> and <mark>Shell</mark>

content:
  - title: Papers # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        description: |
          <span style="font-size: 28px;">
          1. [Wu, W. et al. Acute hypoxia suppresses blood glycolysis in saker falcons (Falco cherrug) via NR3C1-mediated repression of HK1: evidence from hematological and epigenomic profiling. Zool. Res. 46(5), 1165-1174 (2025)](https://www.zoores.ac.cn/en/article/doi/10.24272/j.issn.2095-8137.2025.092)

          2. [Pan, S.-K. et al. Smarter birds, smaller eggs, and less parental care time. Zool. Res. 44, 98–100 (2023).](https://www.zoores.ac.cn/en/article/doi/10.24272/j.issn.2095-8137.2022.283)
          

          
          

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PhD candidate of Genomics
        caption: 2020 - 
        #sub_title: 
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Institute of Zoology, Chinese Academy of Sciences
      - layout: left
        title: Master of Regenerative Medicine
        caption: 2017 - 2020
        #sub_title: 
        description: |
          Medical School, University of Chinese Academy of Sciences

# Footer
footer_show_references: true
references_title: You actually finished reading all of it!

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
